name: Continuous Integration

on: 
  push:
    branches:
      - '*'
      - '!master'

jobs:
  CI-job:
    runs-on: ubuntu-latest
    if: github.
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: yarn
          